/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package logbook.form;

import java.sql.Connection;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;
import db.db;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author keratampan
 */
public class Form_DataKaryawan extends javax.swing.JPanel {

     private Connection conn = new db().connect();
    /**
     * Creates new form Form_DataKaryawan
     */
    public Form_DataKaryawan() {
        initComponents();
        DataAdmin();
        kel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JenisKel = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        roundPanel1 = new logbook.swing.RoundPanel();
        jLabel1 = new javax.swing.JLabel();
        nik = new javax.swing.JTextField();
        btnCari = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        nama = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        telp = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        L = new javax.swing.JRadioButton();
        P = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        cbPwd = new javax.swing.JCheckBox();
        roundPanel2 = new logbook.swing.RoundPanel();
        Jscroll = new javax.swing.JScrollPane();
        admin = new logbook.swing.table.Table();
        roundPanel3 = new logbook.swing.RoundPanel();
        btnTambah = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        kel = new javax.swing.JTextField();

        jPanel1.setBackground(new java.awt.Color(245, 245, 245));

        roundPanel1.setBackground(new java.awt.Color(255, 255, 255));
        roundPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        roundPanel1.setRound(10);

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(125, 125, 125));
        jLabel1.setText("NIK");

        btnCari.setText("Cari");
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(125, 125, 125));
        jLabel2.setText("Username");

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(125, 125, 125));
        jLabel3.setText("Nama");

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(125, 125, 125));
        jLabel4.setText("Email");

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(125, 125, 125));
        jLabel5.setText("Telp");

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(125, 125, 125));
        jLabel6.setText("Jenis Kelamin");

        JenisKel.add(L);
        L.setForeground(new java.awt.Color(125, 125, 125));
        L.setText("Laki Laki");

        JenisKel.add(P);
        P.setForeground(new java.awt.Color(125, 125, 125));
        P.setText("Perempuan");

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(125, 125, 125));
        jLabel7.setText("Password");

        password.setText("jPasswordField1");

        cbPwd.setForeground(new java.awt.Color(125, 125, 125));
        cbPwd.setText("ubah ?");
        cbPwd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPwdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout roundPanel1Layout = new javax.swing.GroupLayout(roundPanel1);
        roundPanel1.setLayout(roundPanel1Layout);
        roundPanel1Layout.setHorizontalGroup(
            roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(roundPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(201, 201, 201))
                    .addGroup(roundPanel1Layout.createSequentialGroup()
                        .addComponent(cbPwd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(roundPanel1Layout.createSequentialGroup()
                                .addComponent(L)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(P))
                            .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel6)
                        .addGroup(roundPanel1Layout.createSequentialGroup()
                            .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel1)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(nik)
                                .addComponent(username)
                                .addComponent(nama)
                                .addComponent(email)
                                .addComponent(telp, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCari, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        roundPanel1Layout.setVerticalGroup(
            roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCari))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(telp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(L)
                    .addComponent(P))
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addGap(4, 4, 4)
                .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbPwd))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        roundPanel2.setBackground(new java.awt.Color(255, 255, 255));
        roundPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        roundPanel2.setRound(10);

        admin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nama", "NIK", "Username", "Email", "No Telp", "JenisKel"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        admin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adminMouseClicked(evt);
            }
        });
        Jscroll.setViewportView(admin);

        javax.swing.GroupLayout roundPanel2Layout = new javax.swing.GroupLayout(roundPanel2);
        roundPanel2.setLayout(roundPanel2Layout);
        roundPanel2Layout.setHorizontalGroup(
            roundPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Jscroll, javax.swing.GroupLayout.DEFAULT_SIZE, 536, Short.MAX_VALUE)
                .addContainerGap())
        );
        roundPanel2Layout.setVerticalGroup(
            roundPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Jscroll, javax.swing.GroupLayout.DEFAULT_SIZE, 537, Short.MAX_VALUE)
                .addContainerGap())
        );

        roundPanel3.setBackground(new java.awt.Color(255, 255, 255));
        roundPanel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        roundPanel3.setRound(10);

        btnTambah.setBackground(new java.awt.Color(33, 186, 69));
        btnTambah.setForeground(new java.awt.Color(255, 255, 255));
        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnUbah.setBackground(new java.awt.Color(255, 153, 51));
        btnUbah.setForeground(new java.awt.Color(255, 255, 255));
        btnUbah.setText("Ubah");
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });

        btnHapus.setBackground(new java.awt.Color(255, 51, 0));
        btnHapus.setForeground(new java.awt.Color(255, 255, 255));
        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnReset.setBackground(new java.awt.Color(153, 153, 153));
        btnReset.setForeground(new java.awt.Color(255, 255, 255));
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout roundPanel3Layout = new javax.swing.GroupLayout(roundPanel3);
        roundPanel3.setLayout(roundPanel3Layout);
        roundPanel3Layout.setHorizontalGroup(
            roundPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnTambah)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnUbah)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnHapus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnReset)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        roundPanel3Layout.setVerticalGroup(
            roundPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(roundPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTambah)
                    .addComponent(btnUbah)
                    .addComponent(btnHapus)
                    .addComponent(btnReset))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        kel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(roundPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(roundPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(kel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(roundPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(roundPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(roundPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(kel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(roundPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(68, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        String nama_adm = nama.getText();
        String nik_adm = nik.getText();
        String email_adm = email.getText();
        String telp_adm = telp.getText();
        this.L.setActionCommand("L");
        this.P.setActionCommand("P");
    
        String kelamin = JenisKel.getSelection().getActionCommand();
        String pwd = new String(password.getPassword());
        String username_adm = username.getText();
        
         String addAdmin = "INSERT INTO admin(nama,nik,email,no_telp,jenis_kelamin,password,username)"+ "VALUES (?,?,?,?,?,?,?)";
         
         try {
           PreparedStatement add = conn.prepareStatement(addAdmin);
           add.setString(1, nama_adm);
           add.setString(2, nik_adm);
           add.setString(3, email_adm);
           add.setString(4, telp_adm);
           add.setString(5, kelamin);
           add.setString(6, pwd);
           add.setString(7, username_adm);
           
           if (nama_adm.isEmpty() || nik_adm.isEmpty() || email_adm.isEmpty() || telp_adm.isEmpty() || kelamin.isEmpty() || pwd.isEmpty() || username_adm.isEmpty()) {
               JOptionPane.showMessageDialog(null,"Form harus diisi semua, Tidak boleh kosong !!");
           }
           else {
               add.execute();
               DataAdmin();
               resetFormAdmin();
               JOptionPane.showMessageDialog(null,"Data Tersimpan");
               
           }
           
       } catch (SQLException ex) {
            Logger.getLogger(Form_DataKaryawan.class.getName()).log(Level.SEVERE, null, ex);
        }
         
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
      String nama_adm = nama.getText();
        String nik_adm = nik.getText();
        String email_adm = email.getText();
        String telp_adm = telp.getText();
        this.L.setActionCommand("L");
        this.P.setActionCommand("P");
    
         String kelamin = JenisKel.getSelection().getActionCommand();
        String pwd = new String(password.getPassword());
        String username_adm = username.getText();
        
        if ( password.isEnabled() ){
            if (pwd.isEmpty()) {
                 JOptionPane.showMessageDialog(null,"Password tidak boleh kosong !!");
            }
            else{
                String ubahAdmin = "UPDATE admin SET nama='"+nama_adm+"', email='"+email_adm+"', no_telp='"+telp_adm+"', jenis_kelamin='"+kelamin+"', username='"+username_adm+"', password='"+pwd+"' WHERE nik="+nik_adm+";";
        
                try {
                    PreparedStatement ubah = conn.prepareStatement(ubahAdmin);
                     ubah.execute();
                     DataAdmin();
                     resetFormAdmin();
                     JOptionPane.showMessageDialog(null,"Data Berhasil Diubah!");    
                }
                catch (SQLException ex) {
                  Logger.getLogger(Form_DataKaryawan.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
        else {
            String ubahAdmin = "UPDATE admin SET nama='"+nama_adm+"', email='"+email_adm+"', no_telp='"+telp_adm+"', jenis_kelamin='"+kelamin+"', username='"+username_adm+"' WHERE nik="+nik_adm+";";
        
            try {
                PreparedStatement ubah = conn.prepareStatement(ubahAdmin);
                 ubah.execute();
                 DataAdmin();
                 resetFormAdmin();
                 JOptionPane.showMessageDialog(null,"Data Berhasil Diubah!");    
            }
            catch (SQLException ex) {
              Logger.getLogger(Form_DataKaryawan.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnUbahActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
       String nik_adm = nik.getText();
       String hapusdata = "DELETE FROM admin WHERE nik="+nik_adm+"";
       
       try {
           PreparedStatement hapus = conn.prepareStatement(hapusdata);
           hapus.execute();
           DataAdmin();
           resetFormAdmin();
           JOptionPane.showMessageDialog(null,"Data Berhasil Dihapus!");    
       }
       catch (SQLException ex) {
              Logger.getLogger(Form_DataKaryawan.class.getName()).log(Level.SEVERE, null, ex);
       }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
         resetFormAdmin();
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        password.setEnabled(false);
        String key_nik = nik.getText();
            System.out.println("Menampilkan data dengan NIK "+key_nik);
     
            if ( key_nik != ""  ) {
                cariDataAdmin(key_nik);
            }else{
                DataAdmin();
            }
    }//GEN-LAST:event_btnCariActionPerformed

    private void adminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminMouseClicked
         int baris = admin.rowAtPoint(evt.getPoint());
        String nama_adm =  admin.getValueAt(baris,0).toString();
        String nik_adm = admin.getValueAt(baris,1).toString();
        String email_adm = admin.getValueAt(baris, 3).toString();
        String telp_adm = admin.getValueAt(baris,4).toString();
        String username_adm = admin.getValueAt(baris, 2).toString();
        String kel = admin.getValueAt(baris,5).toString();
        nama.setText(nama_adm);
        nik.setText(nik_adm);
        email.setText(email_adm);
        telp.setText(telp_adm);
        username.setText(username_adm);
        if (kel.equals("L")  ) {
            L.setSelected(true); 
        } else if (kel.equals("P")) {
            P.setSelected(true); 
        } 
       
        btnUbah.setEnabled(true);
        btnHapus.setEnabled(true);
        btnTambah.setEnabled(false);
        btnReset.setEnabled(true);
        cbPwd.setVisible(true);
        password.setEnabled(false);
        System.out.println("Menampilkan data dengan NIK "+nik);
        
        
    }//GEN-LAST:event_adminMouseClicked

    private void cbPwdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPwdActionPerformed
         if(cbPwd.isSelected()==true){
            password.setEnabled(true);
        }else if(cbPwd.isSelected()==false){
            password.setEnabled(false);
        }
    }//GEN-LAST:event_cbPwdActionPerformed

    private void kelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kelActionPerformed

     private void resetFormAdmin() {
        nama.setText("");
        nik.setText("");
        email.setText("");
        telp.setText("");
        username.setText("");
        password.setText("password123");
        cbPwd.setVisible(false);
        btnTambah.setEnabled(true);
        btnUbah.setEnabled(false);
        btnHapus.setEnabled(false);
        btnReset.setEnabled(false);
        password.setEnabled(true);
        DataAdmin();
        
    }
     
     private void DataAdmin(){
        try{
           
            
            Connection conn = new db().connect();
            Statement show=conn.createStatement();
           
            admin.RemoveElement();
            
            ResultSet query = show.executeQuery("SELECT * from admin");  
            while(query.next()){
                Object[] data={
                    query.getString("nama"),
                    query.getString("nik"),
                    query.getString("username"),
                    query.getString("email"),
                    query.getString("no_telp"),
                    query.getString("jenis_kelamin")
                    
                };
               admin.fixTable(Jscroll);
               admin.addRow(data);
            }                
        } catch (Exception ex) {
        System.err.println(ex.getMessage());
        }
    }
     
    private void cariDataAdmin ( String key_nik ){
        try{
       
            Connection conn = new db().connect();
            Statement show=conn.createStatement();
            
            admin.RemoveElement();
            
            ResultSet query = show.executeQuery("SELECT * from admin where nik='"+key_nik+"' ");  
            while(query.next()){
                Object[] data={
                    query.getString("nama"),
                    query.getString("nik"),
                    query.getString("username"),
                    query.getString("email"),
                    query.getString("no_telp"),
                    query.getString("jenis_kelamin")
                };
                
                nik.setText(query.getString("nik"));
                nama.setText(query.getString("nama"));
                username.setText(query.getString("username"));
                email.setText(query.getString("email"));
                telp.setText(query.getString("no_telp"));
                kel.setText(query.getString("jenis_kelamin"));
  
                 
                if (kel.equals("L")  ) {
                    L.setSelected(true); 
                } else if (kel.equals("P")) {
                    P.setSelected(true); 
                } 
                
                btnUbah.setEnabled(true);
                btnHapus.setEnabled(true);
                btnTambah.setEnabled(false);
                btnReset.setEnabled(true);
                cbPwd.setVisible(true);
                password.setEnabled(false);
                
               admin.addRow(data);
               admin.fixTable(Jscroll);
               
            }                
        } catch (Exception ex) {
        System.err.println(ex.getMessage());
        }
    }
     

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup JenisKel;
    private javax.swing.JScrollPane Jscroll;
    private javax.swing.JRadioButton L;
    private javax.swing.JRadioButton P;
    private logbook.swing.table.Table admin;
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnUbah;
    private javax.swing.JCheckBox cbPwd;
    private javax.swing.JTextField email;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField kel;
    private javax.swing.JTextField nama;
    private javax.swing.JTextField nik;
    private javax.swing.JPasswordField password;
    private logbook.swing.RoundPanel roundPanel1;
    private logbook.swing.RoundPanel roundPanel2;
    private logbook.swing.RoundPanel roundPanel3;
    private javax.swing.JTextField telp;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
